/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#5c3800",
        "on-background": "#191c1d",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed-dim": "#b6c4ff",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "secondary-container": "#6df5e1",
        "on-primary-container": "#90a8ff",
        "on-secondary-fixed": "#00201c",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c5c5d3",
        "background": "#f8f9fa",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed-variant": "#264191",
        "on-surface": "#191c1d",
        "on-primary-fixed": "#00164e",
        "surface-tint": "#4059aa",
        "on-tertiary-fixed": "#2a1700",
        "surface-container": "#edeeef",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-low": "#f3f4f5",
        "primary": "#00236f",
        "primary-container": "#1e3a8a",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-high": "#e7e8e9",
        "on-secondary-container": "#006f64",
        "outline": "#757682",
        "on-secondary-fixed-variant": "#005048",
        "on-tertiary": "#ffffff",
        "secondary": "#006b5f",
        "on-secondary": "#ffffff",
        "tertiary": "#3e2400",
        "on-tertiary-container": "#ef9900",
        "surface": "#f8f9fa",
        "secondary-fixed": "#71f8e4",
        "error": "#ba1a1a",
        "on-surface-variant": "#444651",
        "surface-variant": "#e1e3e4",
        "inverse-surface": "#2e3132",
        "inverse-primary": "#b6c4ff",
        "on-error-container": "#93000a",
        "surface-dim": "#d9dadb",
        "secondary-fixed-dim": "#4fdbc8",
        "primary-fixed": "#dce1ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        gutter: "24px",
        "container-max": "1280px",
        xs: "8px",
        "margin-mobile": "16px",
        base: "4px",
        xxl: "48px",
        xl: "32px",
        md: "16px",
        lg: "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-md":   ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm":    ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm":   ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm":["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md":["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg":    ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":    ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      keyframes: {
        fillBar: {
          from: { width: "0%" },
          to: { width: "var(--target-width, 65%)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "fill-bar": "fillBar 1.2s cubic-bezier(0.4,0,0.2,1) forwards",
      },
    },
  },
  plugins: [],
}
