# Generated by Django 5.1.6 on 2026-06-26 16:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the learning path.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what this learning path covers.')),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], help_text='Target difficulty level of the learning path.', max_length=20)),
            ],
            options={
                'verbose_name': 'Learning Path',
                'verbose_name_plural': 'Learning Paths',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('learner', 'Learner'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='learner', help_text='The role of the user on the platform.', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the course.', max_length=255)),
                ('description', models.TextField(help_text='Detailed course description.')),
                ('thumbnail', models.URLField(blank=True, help_text='URL pointing to the course thumbnail image.', max_length=500, null=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Designates whether this course requires a premium subscription.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the course was created.')),
                ('instructor', models.ForeignKey(help_text="The instructor teaching this course (limited to users with role='instructor').", limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
                ('learning_path', models.ForeignKey(blank=True, help_text='The learning path this course belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.learningpath')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique, immutable identifier for the certificate verification.', unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the certificate was issued.')),
                ('user', models.ForeignKey(help_text='The user receiving the certificate.', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('learning_path', models.ForeignKey(help_text='The completed learning path.', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.learningpath')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the lesson.', max_length=255)),
                ('content_text', models.TextField(blank=True, help_text='Written course material for this lesson (optional).', null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL to the video content for this lesson (optional).', max_length=500, null=True)),
                ('duration_seconds', models.PositiveIntegerField(help_text='Lesson duration in seconds (must be between 3 to 10 minutes: 180s - 600s).', validators=[django.core.validators.MinValueValidator(180, message='Bite-sized lesson duration must be at least 3 minutes (180 seconds).'), django.core.validators.MaxValueValidator(600, message='Bite-sized lesson duration must not exceed 10 minutes (600 seconds).')])),
                ('sort_order', models.PositiveIntegerField(help_text='Order in which this lesson appears in the course.')),
                ('course', models.ForeignKey(help_text='The course this lesson belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('course', 'sort_order')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the quiz.', max_length=255)),
                ('lesson', models.OneToOneField(help_text='The lesson associated with this quiz.', on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The text of the question.')),
                ('explanation', models.TextField(help_text='Explanation of the correct answer to provide instant learner feedback.')),
                ('quiz', models.ForeignKey(help_text='The quiz this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(help_text='The text content of the answer option.', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Check if this option is the correct answer.')),
                ('question', models.ForeignKey(help_text='The quiz question this option belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Option',
                'verbose_name_plural': 'Quiz Options',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, help_text='True if the user has completed this lesson.')),
                ('watched_seconds', models.PositiveIntegerField(default=0, help_text='Number of seconds the user has watched of the lesson video.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='The timestamp when this lesson was completed by the user.', null=True)),
                ('lesson', models.ForeignKey(help_text='The lesson being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
                ('user', models.ForeignKey(help_text='The user studying the lesson.', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progresses',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
